### PR TITLE
Sessions utilisateur/responsable

### PR DESCRIPTION
**Pull request by elisematos**

### CODE REVIEW

**Comment by elisematos** [comment]
https://www.loom.com/share/56229aebe2ac4f5fae1e206fe9cdc197

**Review by Frutios — APPROVED** [review]
Incredible

**Review by RomainClair — CHANGES_REQUESTED** [review]
Useless AppFixtures class

If you want things to be displayed everywhere, you should add them in the base template.

**Comment by elisematos** [comment]
Useless AppFixtures class => Deleted

If you want things to be displayed everywhere, you should add them in the base template. => Done

**Review by RomainClair — APPROVED** [review]

**Pull request merged**
